# Generated by Django 5.2.3 on 2025-06-14 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(max_length=20)),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.TimeField()),
                ("number_of_guests", models.PositiveIntegerField()),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Preferensi meja, alergi, perayaan, dll.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("WAITLISTED", "Waitlisted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["reservation_date", "reservation_time"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Nama Restoran Kami", max_length=100),
                ),
                ("address", models.TextField(default="Alamat Lengkap Restoran")),
                (
                    "phone_number",
                    models.CharField(default="08123456789", max_length=20),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Deskripsi singkat tentang restoran",
                        null=True,
                    ),
                ),
                ("opening_time", models.TimeField(default=datetime.time(10, 0))),
                ("closing_time", models.TimeField(default=datetime.time(22, 0))),
                (
                    "slot_interval_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Interval slot waktu dalam menit (misal: 30 menit)",
                    ),
                ),
                (
                    "max_guests_per_slot",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Total maksimum tamu yang bisa dilayani dalam satu slot waktu",
                    ),
                ),
            ],
        ),
    ]
