# Generated by Django 5.2.3 on 2025-07-26 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0002_reservation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Paket')),
                ('description', models.TextField(help_text='Isi dari paket makanan, misal: Nasi, Ayam Bakar, Teh', verbose_name='Deskripsi Paket')),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga per paket', max_digits=10, verbose_name='Harga')),
            ],
            options={
                'verbose_name': 'Paket Makanan',
                'verbose_name_plural': 'Daftar Paket Makanan',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Ruangan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('capacity', models.PositiveIntegerField(help_text='Kapasitas maksimum tamu untuk ruangan ini', verbose_name='Kapasitas')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Daftar Ruangan',
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time'], 'verbose_name': 'Reservasi', 'verbose_name_plural': 'Semua Reservasi'},
        ),
        migrations.AlterModelOptions(
            name='restaurantprofile',
            options={'verbose_name': 'Profil Restoran', 'verbose_name_plural': 'Profil Restoran'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(max_length=254, verbose_name='Email Tamu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=100, verbose_name='Nama Tamu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(max_length=20, verbose_name='Telepon Tamu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(verbose_name='Jumlah Tamu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(verbose_name='Tanggal Reservasi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(verbose_name='Waktu Reservasi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Preferensi meja, alergi, perayaan, dll.', null=True, verbose_name='Permintaan Khusus'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('WAITLISTED', 'Waitlisted')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Akun Pengguna'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='max_guests_per_slot',
            field=models.PositiveIntegerField(default=20, help_text='Total maksimum tamu yang bisa dilayani dalam satu slot waktu (sekarang digantikan oleh kapasitas per ruangan)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='food_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservasi.foodpackage', verbose_name='Paket Makanan'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservasi.room', verbose_name='Tipe Ruangan'),
        ),
    ]
